using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FFTArchivist
{
    public partial class Constants
    {
        public static Dictionary<int, string> AbilityFormulas = new Dictionary<int, string>
        {
            [0x00] = "Dmg_[Weapon] PE",
            [0x01] = "Dmg_[Weapon] PE",
            [0x02] = "Dmg_[Weapon] 19% Cast Spell Indexed As Status NS PE",
            [0x03] = "Dmg_(WP^2) NS NE",
            [0x04] = "Casts Ice, Fire, Bolt 1/2/3 depending on element NS NE",
            [0x05] = "Dmg_[Weapon] PE",
            [0x06] = "AbsorbHP_[Weapon] NS PE",
            [0x07] = "Heal_[Weapon] NS NE",
            [0x08] = "Dmg_F(MA*Y) ME",
            [0x09] = "Dmg_(Y/100)% Hit_F(MA+X)% ME",
            [0x0A] = "Hit_F(MA+X)% ME",
            [0x0B] = "Hit_F(MA+X)% NE",
            [0x0C] = "Heal_F(MA*Y) NS NE",
            [0x0D] = "Heal_(Y)% Hit_F(MA+X)% NE",
            [0x0E] = "Dmg_(Y)% Hit_F(MA+X)% 100% Status Hide Status",
            [0x0F] = "AbsorbMP_(Y)% Hit_F(MA+X)% NS ME",
            [0x10] = "AbsorbHP_(Y)% Hit_F(MA+X)% NS ME",
            [0x11] = "(Blank)",
            [0x12] = "Set_Quick Hit_F(MA+X)% NS NE",
            [0x13] = "(Blank)",
            [0x14] = "Set_Golem Hit_CasF/100*(MA+X)% GlmHP(TarMaxHP) NS NE",
            [0x15] = "Set_CT00 Hit_F(MA+X)% NS ME",
            [0x16] = "DmgMP_(TarCurMP) Hit_F(MA+X)% NS ME",
            [0x17] = "Dmg_(TarCurHP-1) Hit_F(MA+X)% NS ME",
            [0x18] = "(Blank)",
            [0x19] = "(Blank)",
            [0x1A] = "Hit_F(MA+Y)% ",
            [0x1B] = "DmgMP_(MA+Y)% Hit_F(X)% NS ME",
            [0x1C] = "Hit_(X)% NS NE",
            [0x1D] = "Hit_(X)% NS NE",
            [0x1E] = "Dmg_((MA+Y)*MA/2) #Hit(Rdm{1,X}) ME",
            [0x1F] = "Dmg_((100-CasF)*(100-TarF)*(MA+Y)*MA/2) #Hit(Rdm{1,X}) ME",
            [0x20] = "Dmg_(MA*Y) NE ",
            [0x21] = "DmgMP_(MA*Y) NS NE ",
            [0x22] = "Hit_(100%) Status NE ",
            [0x23] = "Heal_(MA*Y) NS NE ",
            [0x24] = "Dmg_((PA+Y)/2*MA) ME",
            [0x25] = "Equipped:Break Hit_(PA+WP+Y)% NS PE ELSE WeaponStrike ",
            [0x26] = "Equipped:Steal Hit_(SP+X)% NS PE ELSE miss",
            [0x27] = "StealGil_(CasLVL*SP) Hit_(SP+X)% NS PE",
            [0x28] = "StealExp_(Lowest of TarCurExp &amp; SP+Y) Hit_(SP+X)% PE",
            [0x29] = "OppositeSex: Hit_(MA+X)% NE ELSE miss",
            [0x2A] = "Hit_(MA+X)% ",
            [0x2B] = "Hit_(PA+Y)% ",
            [0x2C] = "DmgMP_(Y)% Hit_(PA+Y)% NS PE",
            [0x2D] = "Dmg_(PA*(WP+Y)) PE",
            [0x2E] = "Equipped:Break Dmg_(PA*WP) NS PE ELSE miss",
            [0x2F] = "AbsorbMP_(PA*WP) NS PE",
            [0x30] = "AbsorbHP_(PA*WP) NS PE",
            [0x31] = "Dmg_((PA+Y)/2*PA) PE",
            [0x32] = "Dmg_(Rdm(1..X)*(PA*3+Y)/2) NS PE",
            [0x33] = "Hit_(PA+X)% Status NE",
            [0x34] = "Heal_(PA*Y) HealMP_(PA*Y/2) NS NE",
            [0x35] = "Heal_(Y)% Hit_(PA+X)% Status NE",
            [0x36] = "+PA_(Y) NS NE",
            [0x37] = "Dmg_(Rdm(1..Y)*PA) NS PE",
            [0x38] = "Hit_(100%) Status NE",
            [0x39] = "+SP_(Y) NS NE",
            [0x3A] = "+Brave_(Y) NS NE",
            [0x3B] = "+Brave_(X) +PA/MA/SP_(Y) NS NE",
            [0x3C] = "Heal_(CasMaxHP*2/5) DmgCas_(CasMaxHP/5) Hit_(100%) NS NE",
            [0x3D] = "Hit_(MA+X)% ME",
            [0x3E] = "Dmg_(TarCurHP-1) NS NE",
            [0x3F] = "Hit_(SP+X)% NE",
            [0x40] = "Undead: Hit_(SP+X)% NE ELSE miss",
            [0x41] = "Hit_(MA+X)% Status NE",
            [0x42] = "Dmg_(PA*Y) DmgCas_(PA*Y/X) NS NE",
            [0x43] = "Dmg_(CasMaxHP-CasCurHP) NS NE",
            [0x44] = "Dmg_(TarCurMP) NS NE",
            [0x45] = "Dmg_(TarMaxHP-TarCurHP) NS NE",
            [0x46] = "(Blank)",
            [0x47] = "AbsorbHP_(Y)% 100% Status NE",
            [0x48] = "Heal_(Z*10) NS NE",
            [0x49] = "HealMP_(Z*10) NS NE",
            [0x4A] = "Heal_(100)% HealMP_(100)% NS NE",
            [0x4B] = "Heal_(Rdm(1..9)) 100% Status NE",
            [0x4C] = "Heal_(MA*Y) NS NE",
            [0x4D] = "AbsorbHP_(Y)% Hit_(MA+X)% NS PE",
            [0x4E] = "Dmg_(MA*Y) ME",
            [0x4F] = "Dmg_(CasMaxHP-CasCurHP) Hit_(MA+X)% NS PE",
            [0x50] = "Hit_(MA+X)% Status PE",
            [0x51] = "Hit_(MA+X)% Status NE",
            [0x52] = "Dmg_(CasMaxHP-CasCurHP) 100% Add Status CasterInAoE: DmgSelf_(CasCurHP) NS NE",
            [0x53] = "Dmg_(Y)% Hit_(MA+X)% Status ME",
            [0x54] = "HealMP_(MA*Y) NS NE",
            [0x55] = "-PA_(Y) Hit_(MA+X)% NS ME",
            [0x56] = "-MA_(Y) Hit_(MA+X)% NS ME",
            [0x57] = "+Lvl(1) NS 100% Add Status on Caster NE",
            [0x58] = "Generic: Set_Malboro: Hit(MA+X)% ",
            [0x59] = "-Lvl(1) Hit_(MA+X)% NS ME",
            [0x5A] = "Dragon: Hit(100)%",
            [0x5B] = "Dragon: Heal_(Y)% 100% Add Status NE",
            [0x5C] = "Dragon: +Brave_(X) +PA/MA/SP(Y) NS NE",
            [0x5D] = "Dragon: Set_Quick NS NE",
            [0x5E] = "Dmg_((MA+Y)/2*MA) #Hit_(X+1) Status ME",
            [0x5F] = "Dmg_((MA+Y)/2*MA) Status ME",
            [0x60] = "Dmg_((MA+Y)/2*MA) Status NE",
            [0x61] = "-Brave_(Y) Hit_F(MA+X)% NS ME",
            [0x62] = "-Brave_(Y) Hit_(MA+X)% NS ME",
            [0x63] = "Dmg_(SP*WP) NS PE",
            [0x64] = "Dmg_((PA*Brave/100)*MA) NS NE",
            [0x65] = "<<Sanguine Sword>>",
            [0x66] = "<<Infernal Strike>>",
            [0x67] = "<<Crushing Blow>>",
            [0x68] = "<<Abyssal Blade>>",
            [0x69] = "<<Unholy Sacrifice>>",
            [0x6A] = "<<Barrage>>",
        };
    }
}
