<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
	<Platforms>AnyCPU;x64</Platforms>
	<Version>0.1.0.6</Version>
	<AssemblyName>FFTArchivist</AssemblyName>
    <RootNamespace>FFTArchivist</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <!--<ApplicationIcon>Images\Icons\ic_fluent_history_48_filled.ico</ApplicationIcon>-->
	<StartupObject>FFTArchivist.App</StartupObject>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataSources\NEX\Item - Copy (2)\ItemNEXSource.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\Icons\ic_fluent_history_48_filled.png" />
    <None Remove="Images\Icons\ic_fluent_history_48_filled.svg" />
    <None Remove="Images\Icons\ic_fluent_history_dismiss_48_filled.png" />
    <None Remove="Images\Icons\ic_fluent_history_dismiss_48_filled.svg" />
    <None Remove="Images\Icons\ic_fluent_pen_dismiss_48_filled.png" />
    <None Remove="Images\Icons\ic_fluent_pen_dismiss_48_filled.svg" />
    <None Remove="Images\job_Chocobo.gif" />
    <None Remove="Images\Squire1M-Dead-NW.gif" />
    <None Remove="Preview.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Icons\ic_fluent_history_48_filled.png" />
    <Resource Include="Images\Icons\ic_fluent_history_48_filled.svg" />
    <Resource Include="Images\Icons\ic_fluent_history_dismiss_48_filled.png" />
    <Resource Include="Images\Icons\ic_fluent_history_dismiss_48_filled.svg" />
    <Resource Include="Images\Icons\ic_fluent_pen_dismiss_48_filled.png" />
    <Resource Include="Images\Icons\ic_fluent_pen_dismiss_48_filled.svg" />
    <Resource Include="Images\job_Chocobo.gif" />
    <Resource Include="Images\Squire1M-Dead-NW.gif" />
    <EmbeddedResource Include="Preview.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FF16Framework.Interfaces" Version="1.2.0" />
    <PackageReference Include="FF16Tools.Files" Version="1.4.1" />
    <PackageReference Include="FF16Tools.Pack" Version="1.2.1" />
    <PackageReference Include="fftivc.utility.modloader.Interfaces" Version="1.3.1" />
    <PackageReference Include="fftivc.utility.modloader.Serializers" Version="1.0.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
    <PackageReference Include="Narod.SteamGameFinder" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="3.1.9" />
    <PackageReference Include="Reloaded.Mod.Loader.IO" Version="2.5.0" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.1" />
    <PackageReference Include="YAXLib" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\ErrorSpinner.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\TextBox\TextBoxIntDataItemControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Views\Abilities\SupportAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Abilities\MathAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Abilities\ChargeAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Abilities\JumpAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Abilities\ThrowAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Abilities\ItemAbilityView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ENTDView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\TownView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\UIView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SettingsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PoachView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="ModConfig.json">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\CheckBox\" />
    <Folder Include="Controls\TextBlock\" />
  </ItemGroup>

</Project>
