<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ModConfig.json" />
    <None Remove="Preview.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ModConfig.json">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="Preview.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FF16Tools.Files" Version="1.4.0" />
    <PackageReference Include="FF16Tools.Pack" Version="1.2.1" />
    <PackageReference Include="fftivc.utility.modloader.Interfaces" Version="1.0.3" />
    <PackageReference Include="fftivc.utility.modloader.Serializers" Version="1.0.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0-rc.2.25502.107" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="3.1.9" />
    <PackageReference Include="YAXLib" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PoachView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
